/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.model.Notifications;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-05-24T14:15:13.996Z[GMT]")
@Api(value = "notifications", description = "the notifications API")
public interface NotificationsApi {

    @ApiOperation(value = "Retrieve RTP notifications received from RTP", nickname = "getNotification", notes = "Returns RTP notifications received ", response = Notifications.class, responseContainer = "List", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Returns notifications", response = Notifications.class, responseContainer = "List") })
    @RequestMapping(value = "/notifications",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Notifications>> getNotification();

}
