/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import io.swagger.model.WebHookCallback;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-05-28T15:52:11.162Z[GMT]")
@Api(value = "webhooks", description = "the webhooks API")
public interface WebhooksApi {

    @ApiOperation(value = "Retrived all registered web hooks", nickname = "getWebHooks", notes = "Retrieves all web hooks ", response = WebHookCallback.class, responseContainer = "List", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Registered webhooks", response = WebHookCallback.class, responseContainer = "List") })
    @RequestMapping(value = "/webhooks",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<WebHookCallback>> getWebHooks();


    @ApiOperation(value = "Creates a webhook", nickname = "webhooksPost", notes = "Creates a webhook", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Web hook registered") })
    @RequestMapping(value = "/webhooks",
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> webhooksPost(@ApiParam(value = "Web Hook to add") @Valid @RequestBody WebHookCallback body);

}
